### ISSUE TITLE
Enable the module in Homebrew services

### ISSUE THREAD

**Issue by UsamaKarim** [thevindu-w/clip_share_server#29]
Thanks. Your solution looks good.
1. Can you please make the server as homebrew services?
2. Please let it able to install and update with homebrew

**Comment by thevindu-w** [comment]
Is the requirement of making the app available in homebrew is to make it auto-update?
If so, will it be sufficient to create an auto-update script that can automatically check for updates periodically and install them?
If an auto-update script is not sufficient and homebrew is really necessary, I will try to make it available with homebrew (it may require some time).

**Comment by UsamaKarim** [comment]
> Is the requirement of making the app available in homebrew is to make it auto-update? 
If so, will it be sufficient to create an auto-update script that can automatically check for updates periodically and install them? 
If an auto-update script is not sufficient and homebrew is really necessary, I will try to make it available with homebrew (it may require some time).

homebrew provides ease of access for installing/updating/uninstalling the scripts and apps. Currently the clip share server is automatically being stopped by OS and I have to manually start it again. 
There are few homebrew services I am currently using like `ollama` and `spoofdpi` and these are never automatically stopped and starts again on the system reboot.

**Comment by thevindu-w** [comment]
> Currently the clip share server is automatically being stopped by OS and I have to manually start it again.

Did you install ClipShare using the installer script or did you manually run the executable? If it's installed using the installer script, it should automatically start once you log in. If it stops automatically, that may be a bug. Did you notice when it stops automatically (ex: it doesn't auto-start on boot/login, or it works for some time and stops while you are logged in)? Also, does it just stop accepting connections or does it stop all the clip_share processes? (You can check this by `pgrep clip_share` command. It should have at least 2 processes, but usually there should be 3 processes running)

Btw., I started to create a brew tap for ClipShare, but it might take some time to complete. It would be better if the current issue with ClipShare (being stopped by OS) could be fixed before getting it in Homebrew, as if this gets stopped automatically by OS, this issue can still affect even if you use a brew service for ClipShare.

**Comment by UsamaKarim** [comment]
I installed it with installer.
Currently I have no clue when the connection was stopped. I'll try to debug the issue and let you know if found anything.

Thanks for taking into consideration.

**Comment by UsamaKarim** [comment]
In my recent experience, the server didn't stop. But on every restart of mac it keeps asking for permission of network connection. It there a way to make it allow once?
![Screenshot 2024-11-23 at 5 49 32 PM](https://github.com/user-attachments/assets/89f3f550-5ff7-4cb4-89dd-372f7335ffc3)

**Comment by thevindu-w** [comment]
> In my recent experience, the server didn't stop. But on every restart of mac it keeps asking for permission of network connection. It there a way to make it allow once?

This solution worked for me: [https://stackoverflow.com/a/40067738](https://stackoverflow.com/a/40067738)
You have to replace Xcode in the command in the above thread with `/home/<your-username>/.local/bin/clip_share`. So the commands would look like,
```bash
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
/usr/libexec/ApplicationFirewall/socketfilterfw --add ~/.local/bin/clip_share  # ~ gives your home directory
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
```

**Comment by UsamaKarim** [comment]
Hi, is there any update on installing the module from homebrew?

**Comment by thevindu-w** [comment]
I tried to get it working with Homebrew services. There were some issues with getting the user's home directory (where the config file resides). I'll try to fix those issues and get it working with brew.
Is the network access issue with firewall solved with the above commands (or by other means)? Because even if this is installed with brew, that firewall issue may persist if it's not solved separately.

**Comment by UsamaKarim** [comment]
- If you make any progress with homebrew, I am open to become a tester.

- It wasn’t solved, I still get that popup occasionally.

**Comment by thevindu-w** [comment]
I tried a different method to install the service with brew. Now I got that working and it is now almost complete. Once I complete testing, I'll open the brew tap repo and notify. (ETA: 2 days)

**Comment by thevindu-w** [comment]
Created a brew tap for ClipShare at [github.com/thevindu-w/homebrew-clipshare](https://github.com/thevindu-w/homebrew-clipshare#).
It should install ClipShare server with,
```
brew install thevindu-w/clipshare/clipshare-server
```
After installing, you can create the default config file with, (if not already created)
```
clipshare-initconf
```
Start the service with,
```
brew services start clipshare-server
```

**Comment by UsamaKarim** [comment]
Thank you so much @thevindu-w 
Should I uninstall the previous installed version?

**Comment by thevindu-w** [comment]
Since ClipShare server is now available as a Homebrew service, I will close this issue. If you have any issues with the Homebrew service, feel free to add a comment and I will reopen the issue. If it is a Homebrew specific issue, you may create a new issue in the [homebrew-clipshare](https://github.com/thevindu-w/homebrew-clipshare) repo.
